### ISSUE TITLE
Cant connect to server

### ISSUE THREAD

**Issue by reisxd** [Koodaamo-MareDev/GTPatcher-Android#4]
Hello, its me again.I want to make another server apk, but it dont works(tried on vhosts an works, not the apk.)
ss: https://cdn.discordapp.com/attachments/675029353427632128/704379659189747822/Screenshot_2020-04-27-20-11-22-712_com.rtsoft.growtopia.jpg

**Comment by MarmoriPelaa** [comment]
How long is the server ip address? If it's more than 14 it won't work.
